name: Test Workflow

on: [push]

jobs:
  extensions-cicd:
    runs-on: ubuntu-latest
    steps:
      - name: set env with secrets
        uses: oNaiPs/secrets-to-env-action@v1
        with:
          secrets: ${{ toJSON(secrets) }}
      - name: testing env
        run: |
          env
          echo "Value of BOOMI_CLOUD_URL: $BOOMI_CLOUD_URL"
      