name: Test Workflow

on: [push]

jobs:
  extensions-cicd:
    runs-on: ubuntu-latest
    steps:
      - name: Set env with secrets
        uses: oNaiPs/secrets-to-env-action@v1
        with:
          secrets: ${{ toJSON(secrets) }}
      
      - name: Checkout extension file
        uses: actions/checkout@v3
      
      - name: Read file contents
        id: read_file
        uses: andstor/file-reader-action@v1
        with:
          path: "extensions.json"

      - name: Extension file contents
        run: echo "${{ steps.read_file.outputs.contents }}"

      - name: Replace file contents with env
        run: |
          JSON=`echo ${{ steps.read_file.outputs.contents }}`
          echo $JSON
          TEMP_JSON=$(echo $JSON | perl -pe 's/\$([_A-Z]+)/$ENV{$1}/g')
          echo "TEMP_JSON - \n$TEMP_JSON"
          F_TEMP_JSON=$(echo '{"extensions": '$TEMP_JSON'}' | jq '. + {"environmentId": "${{ secrets.ENVIRONMENT_ID }}"}')
          echo "F_TEMP_JSON - \n$F_TEMP_JSON"
      
      - name: Display replace json
        run: |
          echo $F_TEMP_JSON
      