name: Test Workflow

on: [push]

jobs:
  run-shell-command:
    runs-on: ubuntu-latest
    steps:
      - name: echo
        run: echo "Hello world!"
      - name: view secrets context
        run: |
          while read -d $'\t' -r key value; do
            if [[ $key == *$'\n'* ]]; then
              echo $key'<<EOF' >> $GITHUB_ENV
              echo "$value" >> $GITHUB_ENV
              echo 'EOF' >> $GITHUB_ENV
            elif [[ ! -z $key ]]; then
              echo $key'='$value >> $GITHUB_ENV
            fi
          done< <(jq -j 'to_entries|.[] | "\(.key) \(.value)\t"' <<< "$SECRETS_CONTEXT")
        env:
          SECRETS_CONTEXT: ${{ toJson(secrets) }}
      - name: env check
        run: |
          echo $SAMPLE_URL
          echo $GITHUB_EVENT_NAME
          echo ${{ secrets.SAMPLE_URL }} >> sample.txt
          cat sample.txt
