name: Test Workflow

on: [push]

jobs:
  extensions-cicd:
    runs-on: ubuntu-latest
    steps:
      - name: set env with secrets 
        run: |
          while read -d $'\t' -r key value; do
            if [[ $key == *$'\n'* ]]; then
              echo $key'<<EOF' >> $GITHUB_ENV
              echo "$value" >> $GITHUB_ENV
              echo 'EOF' >> $GITHUB_ENV
            elif [[ ! -z $key ]]; then
              echo $key'='$value >> $GITHUB_ENV
            fi
          done< <(jq -j 'to_entries|.[] | "\(.key) \(.value)\t"' <<< "$SECRETS_CONTEXT")
        env:
          SECRETS_CONTEXT: ${{ toJson(secrets) }}
      - name: checkout extension file
        uses: actions/checkout@v3
      - name: find and replace extension file
        run: |
          cat extensions.json
          perl -pe 's/\$([_A-Z]+)/$ENV{$1}/g' < extensions.json > tmp_extensions.json
      - name: "call extension api using curl"
        uses: indiesdev/curl@v1.1
        with:
          url: https://c01-sg.integrate-test.boomi.com/ws/rest/queryPackagedComponent/v1/PackagedComponent/
          method: "POST"
          accept: 200,201,204
          headers: '{ "Content-Type": "application/json", "Accept": "application/json" }'
          basic-auth-token: ${{ secrets.BOOMI_CLOUD_USER_TOKEN }}
          body: tmp_extensions.json
          timeout: 20000
          log-response: true