name: Test Workflow

on: [push]

jobs:
  extensions-cicd:
    runs-on: ubuntu-latest
    steps:
      - name: set env with secrets 
        run: |
          while read -d $'\t' -r key value; do
            if [[ $key == *$'\n'* ]]; then
              echo $key'<<EOF' >> $GITHUB_ENV
              echo "$value" >> $GITHUB_ENV
              echo 'EOF' >> $GITHUB_ENV
            elif [[ ! -z $key ]]; then
              echo $key'='$value >> $GITHUB_ENV
            fi
          done< <(jq -j 'to_entries|.[] | "\(.key) \(.value)\t"' <<< "$SECRETS_CONTEXT")
        env:
          SECRETS_CONTEXT: ${{ toJson(secrets) }}
      - name: checkout files
        uses: actions/checkout@v3
      - name: List Files After Checkout
        run: |
          pwd
          ls -a
          cat extensions.json
          perl -pe 's/\$([_A-Z]+)/$ENV{$1}/g' < extensions.json > tmp_extensions.json
          cat tmp_extensions.json
          curl -X POST -k -H 'Content-Type: application/json' -H 'Accept: application/json' -H 'Authorization: Basic dHJhaW5pbmdwcmFnYWRpc2hndW5hc2VrYS0wTTNQN1IuMzhQNzNaOjNkODUxM2M5LTIwZjUtNDg5Yy1hYTU2LWU3YTQ0YWZmYmI5Yw==' -i 'https://c01-sg.integrate-test.boomi.com/ws/rest/queryPackagedComponent/v1/PackagedComponent/' --data @tmp_extension.json
