name: Test Workflow

on: [push]

jobs:
  run-build:
    runs-on: ubuntu-latest
    steps:
      - name: view secrets context
        run: |
          while read -d $'\t' -r key value; do
            if [[ $key == *$'\n'* ]]; then
              echo $key'<<EOF' >> $GITHUB_ENV
              echo "$value" >> $GITHUB_ENV
              echo 'EOF' >> $GITHUB_ENV
            elif [[ ! -z $key ]]; then
              echo $key'='$value >> $GITHUB_ENV
            fi
          done< <(jq -j 'to_entries|.[] | "\(.key) \(.value)\t"' <<< "$SECRETS_CONTEXT")
        env:
          SECRETS_CONTEXT: ${{ toJson(secrets) }}
      - name: Checkout
        uses: actions/checkout@v3
      - name: List Files After Checkout
        run: |
          pwd
          ls -a
          echo "$(cat extensions.json)"
          perl -V
