name: Test Workflow

on: [push]

jobs:
  extensions-cicd:
    runs-on: ubuntu-latest
    steps:
      - name: Set env with secrets
        uses: oNaiPs/secrets-to-env-action@v1
        with:
          secrets: ${{ toJSON(secrets) }}
      
      - name: Checkout extension file
        uses: actions/checkout@v3
      
      - name: Read file contents
        id: read_file
        uses: andstor/file-reader-action@v1
        with:
          path: "extensions.json"

      - name: Extension file contents
        run: |
          echo "${{ steps.read_file.outputs.contents }}"

      - name: Replace file contents with env
        id: replace_env
        run: |
          F_TEMP_JSON=$(echo '{"extensions": '$(echo '${{ steps.read_file.outputs.contents }}' | perl -pe 's/\$([_A-Z]+)/$ENV{$1}/g')'}' | jq '. + {"environmentId": "${{ secrets.ENVIRONMENT_ID }}"}')
      
      - name: Display replace json
        run: |
          echo $F_TEMP_JSON
          echo "${{ steps.replace_env.outputs.F_TEMP_JSON }}"
      